version: "3"
services:
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  vote:
    build: ./docker-voting-app-new/vote
    ports:
      - 1000:80
  result:
    build: ./docker-voting-app-new/result
    ports:
      - 1001:80
  worker:
    build: ./docker-voting-app-new/worker


